### ISSUE TITLE
Check sur les templates

### ISSUE THREAD

**Issue by PBYetml** [blitshteynjacobES/Fille_Template_C#1]
Pour moi, je vous valide vos templates => version [ENG] ou [FR]

**Comment by PBYetml** [comment]
Oups parlé un peu vide => 

dans vos deux headerfiles 

https://github.com/blitshteynjacobES/Fille_Template_C/blob/600995789c633f45872ac574100ad77bea9bf11a/templates/Template_eng.h#L27 ou https://github.com/blitshteynjacobES/Fille_Template_C/blob/600995789c633f45872ac574100ad77bea9bf11a/templates/Template_fr.h#L27

les constantes ou autres déclarations se font toutes dans le `#define`
´´C 
#define NOM_FICHIER_H

vos différentes déclarations et prototypes !!! 

#end if ´´

**Comment by blitshteynjacobES** [comment]
j'ai corriger ce que vous m'avez montrer et déjà push la nouvelle version. autrement, est-ce qu'il y a autre chose que je devrais / pourrais ajouter ou corriger ?

**Comment by blitshteynjacobES** [comment]
merci de votre aide
